### PR TITLE
added option to scale plots automatically based off screen width

### PR DESCRIPTION
**Pull request by Ashton-Sidhu**
Added keyword arg `sizing_mode` so plots with large amount of x axis values aren't compressed. It also allows figures to be scaled to the width or height of the cell so it is compatible across screen types instead of hard coding or playing around with the figsize.

### CODE REVIEW

**Comment by PatrikHlobil** [comment]
Hi @Ashton-Sidhu ,

thanks for contributing to **Pandas-Bokeh**. Could you provide an example of a nice use of the sizing_mode option. Maybe in the section about layouts in the README.md (https://github.com/PatrikHlobil/Pandas-Bokeh#dashboard-layouts). 

Best,

Patrik

**Comment by PatrikHlobil** [comment]
Hi @Ashton-Sidhu ,

Wow this looks great. Do you also want to add a test for this (basically just running the example you showed in the readme)? If not I would take care of it. 

Best Patrik

**Comment by Ashton-Sidhu** [comment]
For sure I will add that test tonight!

**Comment by PatrikHlobil** [comment]
@Ashton-Sidhu , great. Then I wait with merging. Thanks a lot ;)

**Comment by Ashton-Sidhu** [comment]
Added ! Thanks @PatrikHlobil

**Comment by PatrikHlobil** [comment]
@Ashton-Sidhu :Perfect, looks great 👍🏼. Cool that you sorted the imports by buildins and names. Did you do this by hand or do you have some formatted for that?

Thanks again for your contribution, without people like you it wouldn’t be possible to maintain and improve such a library 😁.

Best Patrik

**Comment by Ashton-Sidhu** [comment]
@PatrikHlobil It's an option you can enable in vscode, which I find super handy to help standardize and organize imports in large projects. I can send you the config I use if you want!

No problem! I'm actually creating a library that's a collection of data science/ ml engineering techniques that helps automate and enhance our analysis and I really enjoy using your library and the level of automation it provides and I wanted to include it to make it even easier to visualize and present data.

Thanks for creating this library and making it usable by everyone!

**Comment by PatrikHlobil** [comment]
@Ashton-Sidhu ,

I already had a look at your library, a really ambitious project. Looks really cool, I hope that I can do more Data Science stuff in the near future, but at the moment most of my work is more related to Data Engineering (which I also like to so 😉) within a Airflow/Hadoop ecoystem. 

When do you think you get to the phase with the Pyspark support?

Could you please send me the vs code settings, really like that feature 😊

Best Patrik

**Comment by Ashton-Sidhu** [comment]
@PatrikHlobil If you ever use it, I would appreciate your feedback! Ohh nice we're thinking about deploying a hadoop ecosystem at work in our lab. 

So right now the library is at a place where a good chunk of my work has been automated so I'm starting to introduce it to other members of my team and other data scientists at work to hopefully help and advance it. If that happens I can start with the deep learning / spark integration - so rough time line maybe another month or two.

Sure I can email it to you?

**Pull request merged**
